### ISSUE TITLE
cum ai face daca ar trebui sa sa acoperi si cazul in care ziua de nastere a trecut sau nu. Cat mai simplu

### ISSUE THREAD

**Issue by stefanbulzan** [alexandrutoma6/beta-curs-12-homework#1]
https://github.com/alexandrutoma6/beta-curs-12-homework/blob/2ed58342111a372262be33adb572e74c33b33dfb/src/org/beta/curs12/homework/ex1/calculators/BirthYearCalculator.java#L17

**Comment by alexandrutoma6** [comment]
am introdus un flag in BirthCalculator prin care se reprezinta daca ziua de nastere a fost sau nu acest an
